vich_uploader:
    db_driver: orm

    mappings:
        avatars:
            uri_prefix: /images/avatars
            upload_destination: '%kernel.project_dir%/public/images/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        sponsors:
            uri_prefix: /images/sponsors
            upload_destination: '%kernel.project_dir%/public/images/sponsors'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        recipes:
            uri_prefix: /images/recipes
            upload_destination: '%kernel.project_dir%/public/images/recipes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
